### ISSUE TITLE
msn animated logo disappears when you click on any server

### ISSUE THREAD

**Issue by pneumo-ultra-microscopico** [numoder/dsn10-theme#1]
![Capture](https://github.com/AnthonyM04/msn-dscrd/assets/95929538/fc86781e-cb33-43d6-82fd-a7783844f32b)

**Comment by numoder** [comment]
it appears all the images i have used for buttons and such are missing! im going to find a website to host them instead of discord and ill get back to you

**Comment by numoder** [comment]
@CogumeloDoZap just updated it, install the discordlivemessenger.css let me know if it works!

**Comment by pneumo-ultra-microscopico** [comment]
it keeps the same.
![image](https://github.com/numoder/dlm7-theme/assets/95929538/738c1a7b-c917-4fc5-82e2-3a02b5a6337f)

**Comment by numoder** [comment]
i hate to ask but have you downloaded the updated [discordlivemessenger.theme.css](https://github.com/numoder/dlm7-theme/blob/main/discordlivemessenger.theme.css) ? i made some changes so you wont have to install each new update manually 😅 sorry!

**Comment by pneumo-ultra-microscopico** [comment]
i should copy discordlivemessenger.theme.css into Custom CSS editor, right?

**Comment by numoder** [comment]
that works too! but you can also download it as a vencord or betterdiscord theme as well

**Comment by pneumo-ultra-microscopico** [comment]
![image](https://github.com/numoder/dlm7-theme/assets/95929538/8c51ebec-61d9-4a96-80fd-9a0cc722df6f)
theme won't load when i use discordlivemessenger.theme.css. Am i doing something wrong?

**Comment by pneumo-ultra-microscopico** [comment]
seems to work partially when i copy dlm-general.css into custom css editor

**Comment by numoder** [comment]
did you save it?

**Comment by pneumo-ultra-microscopico** [comment]
yes

**Comment by numoder** [comment]
what does your discord look like right now?

**Comment by pneumo-ultra-microscopico** [comment]
Discord didn't changed with discordlivemessenger.theme.cs

**Comment by numoder** [comment]
strange 🤔

**Comment by numoder** [comment]
okay i found out the solution
better discord doesn't accept raw links, and i need to switch my links to github pages instead.
getting on that now

**Comment by pneumo-ultra-microscopico** [comment]
![image](https://github.com/numoder/dlm7-theme/assets/95929538/658cb365-0486-4662-83b5-797b66226524)
this icon wasn't visible a second ago, just appeared after sometime with discord running.

**Comment by numoder** [comment]
its finally working 😩 try copying these and lemme know if anything happens

@import url('https://numoder.github.io/dlm7-theme/dlm-general.css');
@import url('https://numoder.github.io/dlm7-theme/dlm-icons.css');
@import url('https://numoder.github.io/dlm7-theme/dlm-server.css');
@import url('https://numoder.github.io/dlm7-theme/dlm-friends.css');
@import url('https://numoder.github.io/dlm7-theme/dlm-settings.css');

**Comment by pneumo-ultra-microscopico** [comment]
Sorry if i say something that might sound rude, my english is not one of the best

**Comment by numoder** [comment]
omg this shouldnt have taken so long 😭 try copying these and let me know if it works

@import url('https://numoder.github.io/dlm7-theme/dlm-general.css');
@import url('https://numoder.github.io/dlm7-theme/dlm-icons.css');
@import url('https://numoder.github.io/dlm7-theme/dlm-server.css');
@import url('https://numoder.github.io/dlm7-theme/dlm-friends.css');
@import url('https://numoder.github.io/dlm7-theme/dlm-settings.css');

**Comment by pneumo-ultra-microscopico** [comment]
![image](https://github.com/numoder/dlm7-theme/assets/95929538/33bf606d-45ce-47b8-8ace-acfcd804abc7)

**Comment by numoder** [comment]
@CogumeloDoZap your english is perfectly fine friend! no problems :)

**Comment by pneumo-ultra-microscopico** [comment]
seems it's working well now. Will you close the issue?

**Comment by numoder** [comment]
yep! gotit
