### ISSUE TITLE
The right side of the top bar is asymmetrical

### ISSUE THREAD

**Issue by FruitPunchy0** [numoder/dsn10-theme#14]
![image](https://github.com/numoder/dsn10-theme/assets/166885296/628e4f03-13a4-433b-859c-495acb98e359)
(btw, sorry if I'm uploading too much issues at once, I know you're a busy person and have things to do, but I just like helping people out the best I can)

**Comment by numoder** [comment]
DW about it I really appreciate it and I'll get back to each issue very soon

**Comment by numoder** [comment]
> ![image](https://private-user-images.githubusercontent.com/166885296/325791961-628e4f03-13a4-433b-859c-495acb98e359.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MDQ0NjMsIm5iZiI6MTcxNDUwNDE2MywicGF0aCI6Ii8xNjY4ODUyOTYvMzI1NzkxOTYxLTYyOGU0ZjAzLTEzYTQtNDMzYi04NTljLTQ5NWFjYjk4ZTM1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxOTA5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGE0MGMyOTM4YmYxZDI5YjZkNTE2NmMxY2QxMDhmYzRhNjJiYTBjMmZhZDBkOWY3MmEzMzczMTNlZjRmNDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7BhrGzR5uRl8oua2lEs8gYHJK8WLBwsEAd_wzBIWid8) 

i cant seem to reproduce this error, what are you using for discord + are you using any plugins?

**Comment by numoder** [comment]
for some reason this was only on betterdiscord but its fixed now

**Comment by FruitPunchy0** [comment]
> for some reason this was only on betterdiscord but its fixed now

strange because I'm using vencord. At least it's fixed now though
