### ISSUE TITLE
All BD themes completely broken after latest Discord update

### ISSUE THREAD

**Issue by SquidManNuva** [numoder/dsn10-theme#2]
![image](https://github.com/numoder/dsn10-theme/assets/128169943/066cbece-5284-4e16-b61c-ecdf0bf31581)

**Comment by SquidManNuva** [comment]
If you're looking for help, I suggest trying to get in contact with the DTM-2k/08 dev. They've already figured out how to get their themes working again.

**Comment by numoder** [comment]
a few things are broken but it should be better now

**Comment by numoder** [comment]
still working on it
