### ISSUE TITLE
User buttons kinda cut off?

### ISSUE THREAD

**Issue by ShokCat** [numoder/dsn10-theme#24]
Dont know if this is due to me using retrobar and a custom msstyle but for some reason the bottom left corner buttons seem to be cut off by the taskbar and maybe a tiny bit smaller? Dont know if this is due to a setting in discord or if its something else.
![image](https://github.com/numoder/dsn10-theme/assets/126297961/1895c8aa-e3b3-44b6-bf61-ea9561e8934f)

**Comment by ShokCat** [comment]
Just found out that it was the AIO version causing this problem, idk how much that would help out

**Comment by numoder** [comment]
> Just found out that it was the AIO version causing this problem, idk how much that would help out

my bad, i should probably update it
