### ISSUE TITLE
Avatar icon is extremely bitcrunched, text is overlapping itself

### ISSUE THREAD

**Issue by FruitPunchy0** [numoder/dsn10-theme#3]
There are some instances I immediately noticed where the text overlaps itself with other text. I'm assuming this is going to be fixed soon, but I still would like to point that out.
![image](https://github.com/numoder/dsn10-theme/assets/166885296/8d0655f7-52ea-4a4d-8836-37935f53e47d)
![image](https://github.com/numoder/dsn10-theme/assets/166885296/9eac4d7e-087a-4653-abb0-5957fb323181)
Apparently, the MSN icon that replaces the DM message icon slightly obscures incoming DM's as well?
![image](https://github.com/numoder/dsn10-theme/assets/166885296/cffc934b-f887-429f-b17f-0ebaef48fa1d)

(btw hi, this is my very first post on github)

**Comment by numoder** [comment]
unfortunately the avatar icon in the bottom panel is rendered at 32x32 in the link :/ the only thing i could do is offer a way for users to put in a link to their profile picture with a variable or something
![image](https://github.com/numoder/dsn10-theme/assets/72421281/6ac4772a-1b65-4f1a-bcdb-7fa287ff7814)

i wasnt able to reproduce the MSN icon being farther down like that, what modificated version of discord are you using/ what platform? this pic is vencord no plugins
![image](https://github.com/numoder/dsn10-theme/assets/72421281/02c1432a-cafa-43fc-b20f-7f2c8d6e87c2)

ive moved down the friend message button along with the text in the bottom panel 
![image](https://github.com/numoder/dsn10-theme/assets/72421281/634085c1-2177-42b2-bd75-eea1898cd3b4)
![image](https://github.com/numoder/dsn10-theme/assets/72421281/55557864-4e05-4b66-9b53-f7b0f33b9f50)

**Comment by numoder** [comment]
ive updated [ DSNONLINE.CSS](https://github.com/numoder/dsn10-theme/releases/download/v2.0/dsnonline.css) with instructions on how to fix the pixelated profile pic

**Comment by FruitPunchy0** [comment]
> unfortunately the avatar icon in the bottom panel is rendered at 32x32 in the link :/ the only thing i could do is offer a way for users to put in a link to their profile picture with a variable or something ![image](https://private-user-images.githubusercontent.com/72421281/322172191-6ac4772a-1b65-4f1a-bcdb-7fa287ff7814.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5OTQwMDQsIm5iZiI6MTcxMjk5MzcwNCwicGF0aCI6Ii83MjQyMTI4MS8zMjIxNzIxOTEtNmFjNDc3MmEtMWI2NS00ZjFhLWJjZGItN2ZhMjg3ZmY3ODE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDA3MzUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkODgzMjlmNDY2NTM4NzA1NWIyYTdlOWQzNmIwZTJkN2ZlNjBlMmVhOGE5MmFhMjg4ZmFiMjY3OTgxMDUyMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dt2mJVWo57jWSUeBTWwQn_4WetwK1H_Yv8W7-Esz94E)
> 
> i wasnt able to reproduce the MSN icon being farther down like that, what modificated version of discord are you using/ what platform? this pic is vencord no plugins ![image](https://private-user-images.githubusercontent.com/72421281/322172401-02c1432a-cafa-43fc-b20f-7f2c8d6e87c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5OTQwMDQsIm5iZiI6MTcxMjk5MzcwNCwicGF0aCI6Ii83MjQyMTI4MS8zMjIxNzI0MDEtMDJjMTQzMmEtY2FmYS00M2ZjLWIyMGYtN2YyYzhkNmU4N2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDA3MzUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNmZiZDRjN2RjNTBlMzdiNmVlYTBiYTcwMzgzNGExYzQxY2Y2NmJiNzNlOGUwY2FlZWEwOGYyMDliZDUwOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6gU40-13r00HdG_tnD8XtEqm4nKTs710tU9j-fe4yGc)
> 
> ive moved down the friend message button along with the text in the bottom panel ![image](https://private-user-images.githubusercontent.com/72421281/322172715-634085c1-2177-42b2-bd75-eea1898cd3b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5OTQwMDQsIm5iZiI6MTcxMjk5MzcwNCwicGF0aCI6Ii83MjQyMTI4MS8zMjIxNzI3MTUtNjM0MDg1YzEtMjE3Ny00MmIyLWJkNzUtZWVhMTg5OGNkM2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDA3MzUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NjI3NDBjMDNmNzBkNWZkMmU2NjgyNjdiZGZhMWI0NGEwOWMwZDM1Mjg1MzlhZTg3ZjFlMzE0OTEzZWI4NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iOngECn4XvG67mhW5KoMR90fZqMPxRP86AQsruSamOE) ![image](https://private-user-images.githubusercontent.com/72421281/322172720-55557864-4e05-4b66-9b53-f7b0f33b9f50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5OTQwMDQsIm5iZiI6MTcxMjk5MzcwNCwicGF0aCI6Ii83MjQyMTI4MS8zMjIxNzI3MjAtNTU1NTc4NjQtNGUwNS00YjY2LTliNTMtZjdiMGYzM2I5ZjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDA3MzUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNTI0MzcwZTEzZGIxOTkyMDk5MmE3MzIwMWMxNDg3NTllNmRjZTYwNDcyNTBhNGQ4NDlkYjUwNDYwZjJjNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4m29YBEiuITK-DtrWERQ7w5grAJqjEbmS_nkg9IeAn4)

I'm using betterdiscord. I never looked into the differences between betterdiscord and vencord. Are there any pros from using vencord than betterdiscord?

**Comment by FruitPunchy0** [comment]
![image](https://github.com/numoder/dsn10-theme/assets/166885296/bdd4ebb5-c3e9-4132-8828-f49ffae2234b)
New issue..? I switched over to vencord after uninstalling betterdiscord and now the dm icon is the default one until I highlight my mouse over it?

**Comment by numoder** [comment]
> I'm using betterdiscord. I never looked into the differences between betterdiscord and vencord. Are there any pros from using vencord than betterdiscord?

just some small changes i have to make to make it work best with each version but it shouldnt be much difference

**Comment by numoder** [comment]
> New issue..? I switched over to vencord after uninstalling betterdiscord and now the dm icon is the default one until I highlight my mouse over it?

fixed

**Comment by FruitPunchy0** [comment]
![image](https://github.com/numoder/dsn10-theme/assets/166885296/bb47df44-d68e-4112-86ca-ebc011c90853)
When I am dragging and dropping in files, there seems to be a weird visual glitch where the channels area suddenly shift into dark mode

**Comment by FruitPunchy0** [comment]
![image](https://github.com/numoder/dsn10-theme/assets/166885296/39f654f7-4475-4f9c-ab39-1fed9be77127)
New issue where when I am dragging and dropping in files, the channels section in servers changes to the default discord dark theme

**Comment by FruitPunchy0** [comment]
![image](https://github.com/numoder/dsn10-theme/assets/166885296/4e4f4bc5-dc7a-4dca-a0f0-c33fad1091ba)
New issue where when I am dragging and dropping files, the channels section reverts to the default discord dark mode rather than being in accordance to the new theme

**Comment by numoder** [comment]
>  New issue where when I am dragging and dropping files, the channels section reverts to the default discord dark mode rather than being in accordance to the new theme

fixed
![image](https://github.com/numoder/dsn10-theme/assets/72421281/5021f113-5803-4e9e-82b8-32793580eab7)

**Comment by numoder** [comment]
thank you for reporting all these bugs 😊 let me know if u find anything else

**Comment by FruitPunchy0** [comment]
no problem! I'll be happy to be a bug tester!
