### ISSUE TITLE
New issue: When voice chatting, the ring shown when talking is circular and not square like the icon

### ISSUE THREAD

**Issue by FruitPunchy0** [numoder/dsn10-theme#5]
![image](https://github.com/numoder/dsn10-theme/assets/166885296/e2317499-10f4-47ed-9527-107ccce18a3f)

**Comment by numoder** [comment]
![image](https://github.com/numoder/dsn10-theme/assets/72421281/745d46ad-e930-4a06-9e3c-f37c363080cd)
got it
