### ISSUE TITLE
at the beginning of a channel in a server, it shows a greyed out icon at the top of the page

### ISSUE THREAD

**Issue by FruitPunchy0** [numoder/dsn10-theme#7]
![image](https://github.com/numoder/dsn10-theme/assets/166885296/69a3c42c-5804-4383-9268-8547fd85ad4a)

**Comment by numoder** [comment]
![image](https://github.com/numoder/dsn10-theme/assets/72421281/83b7da16-0b3a-4dee-b2f1-4b43b8759c8f)
fixed
